SUPABASE_URL = 'https://mwhhseuqzoudvibeyvrm.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13aGhzZXVxem91ZHZpYmV5dnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc4MjU4ODQsImV4cCI6MjAyMzQwMTg4NH0.zIivcK4C4B4k-oVhAaM1wAq1ViDAHCFeUGk684amlAs'
APP_SECRET_KEY = 'thisisAVerysuperSecretKey'
RAZORPAY_KEY_ID = ''
RAZORPAY_KEY_SECRET = ''

module.exports = {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  APP_SECRET_KEY,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET
}
