SUPABASE_URL = 'https://mwhhseuqzoudvibeyvrm.supabase.co'
SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im13aGhzZXVxem91ZHZpYmV5dnJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDc4MjU4ODQsImV4cCI6MjAyMzQwMTg4NH0.zIivcK4C4B4k-oVhAaM1wAq1ViDAHCFeUGk684amlAs'
APP_SECRET_KEY = 'thisisAVerysuperSecretKey'
RAZORPAY_KEY_ID = ''
RAZORPAY_KEY_SECRET = ''
GMAIL_SECRET_KEY = 'tqxb vyrl ewmc cejh'
DYTE_ORG_ID = '81c4e94c-f699-4b5f-af86-e0ac610857ca'
DYTE_API_KEY = 'f5bf22ca7f8c7c620868'

module.exports = {
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  APP_SECRET_KEY,
  RAZORPAY_KEY_ID,
  RAZORPAY_KEY_SECRET,
  GMAIL_SECRET_KEY,
  DYTE_ORG_ID,
  DYTE_API_KEY
}
